### PR TITLE
Fix: SnackBar instead of toast if internet is not connected in charge…

### LINKED ISSUE #168: UI enhancement : SnackBar instead of toast if internet is not connected in charges fragment
**Summary:**

if we pull to refresh data in charges fragment when internet is not connected, a toast pops with error message "Error loading in client charges", instead of this toast a SnackBar with same message will enhance the UI 

**Steps to reproduce:**

Step1: login into app
Step2: go to charges fragment
Step3: give no internet access to your phone
Step4: pull to refresh data and a toast will appear.

**Expected behavior:**

A SnackBar instead of toast on charges fragment will enhance the UI of app.
screenshot_20170310-110803

**Observed behavior:**

A Toast on pull to refresh data in charges fragment
screenshot_20170310-110714

**Device and Android version:**

Stock Android 7.1.1

@therajanmaurya i would like to work on this, please assign it to me. Thanks

### PR DESCRIPTION
**Pull request by Rishabhk07**
Fix: SnackBar instead of toast if internet is not connected in charges fragment, fixes #168

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `MifosStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by Rishabhk07** [comment]
@therajanmaurya please review. Thanks :)

File: app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientChargeFragment.java [hunk 1]
```diff
@@ -103,7 +104,7 @@ public void onRefresh() {
 
     @Override
     public void showErrorFetchingClientCharges(String message) {
-        Toast.makeText(getActivity(), message, Toast.LENGTH_LONG).show();
+        Toaster.show(getView() , message);
```
Comment (therajanmaurya) [inline app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientChargeFragment.java]: @Rishabhk07 remove the getView() and pass the `rooView` as a parameter.

**Review by therajanmaurya — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientChargeFragment.java (hunk 1 above)
Comment (Rishabhk07) [reply app/src/main/java/org/mifos/selfserviceapp/ui/fragments/ClientChargeFragment.java]: @therajanmaurya Fixed the changes, used rootView instead of getView().

**Review by therajanmaurya — APPROVED** [review]
