### PR TITLE
Fix #703 : Forms not loaded, when no Internet Connection [used Sweet Error Library]

### LINKED ISSUE #703: App crashes and causes UX issues when user submit or enter fragment for any form in Offline Mode
**Summary:**

App crashes and causes UX issues when user submit or enter fragment for any form in Offline Mode (Dropdown contains empty value)

**Steps to reproduce:**

Open Transfer or Beneficiary Form in offline mode

**Expected behaviour:**

I guess, a better approach will be to show "No Internet" message on Screen

**Observed behaviour:**

Instead, it shows the form with no dropdowns which cause Crashing of app

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

**(App crashes)**

**(User will face difficulty, cause UX issues)**
issue_beneficiary

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #703

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 @droidchef @satyan Please review this PR.

**Comment by therajanmaurya** [comment]
@miPlodder Please use Sweet Error UI.

**Comment by miPlodder** [comment]
@therajanmaurya Please review the PR. I have made the requested changes and updated the GIF's.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java [hunk 1]
```diff
@@ -60,6 +63,12 @@
     @BindView(R.id.til_beneficiary_name)
     TextInputLayout tilBeneficiaryName;
 
+    @BindView(R.id.layout_error)
+    View layout_error;
+
+    @BindView(R.id.view_flipper)
```
Comment (therajanmaurya) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java]: id name is not, make it nsvBeneficiary

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java [hunk 2]
```diff
@@ -60,6 +63,12 @@
     @BindView(R.id.til_beneficiary_name)
     TextInputLayout tilBeneficiaryName;
 
+    @BindView(R.id.layout_error)
+    View layout_error;
```
Comment (therajanmaurya) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java]: use camel case naming convention, it should be layoutError

**Review by therajanmaurya — CHANGES_REQUESTED** [review]

**Comment by therajanmaurya** [comment]
@miPlodder Fix the conflict and make requested changes.

**Comment by miPlodder** [comment]
@therajanmaurya Please review this PR again.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryListFragment.java [hunk 3]
```diff
@@ -94,8 +94,10 @@ public View onCreateView(LayoutInflater inflater, @Nullable ViewGroup container,
     @Override
     public void onSaveInstanceState(Bundle outState) {
         super.onSaveInstanceState(outState);
-        outState.putParcelableArrayList(Constants.BENEFICIARY, new ArrayList<Parcelable>(
-                beneficiaryList));
+        if (beneficiaryList != null) {
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryListFragment.java:97]: @therajanmaurya Without null pointer check, the app was crashing. (Maybe because of migration from Fragment to activity)

**Review by therajanmaurya — APPROVED** [review]
