### PR TITLE
fix: Transfer Screens accepting '0' as Amount

### LINKED ISSUE #186: Transfer amount Accepting '0'
the amount field in transfer layout accepting 0 amount @therajanmaurya  i would like to fix this bug...
screenshot_20170316-022204

### PR DESCRIPTION
**Pull request by dilpreet2028**
Fixes #186 
I have also added : 
```
InputMethodManager imm = (InputMethodManager) MifosSelfServiceApp.getContext(). getSystemService(Context.INPUT_METHOD_SERVICE);
imm.hideSoftInputFromWindow(view.getWindowToken(), 0);
```
which hides keyboard(if any) before displaying the snackbar.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: app/src/main/java/org/mifos/selfserviceapp/utils/Toaster.java [hunk 1]
```diff
@@ -14,6 +16,9 @@
     public static final int SHORT = Snackbar.LENGTH_SHORT;
 
     public static void show(View view, String text, int duration) {
+        InputMethodManager imm = (InputMethodManager) MifosSelfServiceApp.getContext().
+                getSystemService(Context.INPUT_METHOD_SERVICE);
+        imm.hideSoftInputFromWindow(view.getWindowToken(), 0);
```
Comment (therajanmaurya) [inline app/src/main/java/org/mifos/selfserviceapp/utils/Toaster.java:21]: Good work 👍

**Review by therajanmaurya — CHANGES_REQUESTED** [review]

**Review by therajanmaurya — APPROVED** [review]
