### PR TITLE
Fixed the filters in savings account

### LINKED ISSUE #1902: Filters aren't working properly in the Accounts section
**Summary:**

The filters aren't working the way they are supposed to

**Steps to reproduce:**

https://user-images.githubusercontent.com/90026952/216436584-8f528a89-1bcc-4b28-a511-385db8e3d67e.mp4

**Expected behaviour:**
The check box should be clickable and list out the appropriate results

**Observed behaviour:**

The check box isn't working and after clicking on "Filter" it shows no savings account found even though such an account exists

**Device and Android version:**

Device : Samsung M11
Android: 11

### PR DESCRIPTION
**Pull request by PratyushSingh07**
Fixes #1902 

https://user-images.githubusercontent.com/90026952/221344466-07bc6fe8-82c3-4545-ae28-b9dd2c7d28a7.mp4

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: app/src/main/java/org/mifos/mobile/ui/adapters/CheckBoxAdapter.kt [hunk 1]
```diff
@@ -29,10 +29,13 @@ class CheckBoxAdapter @Inject constructor() :
     }
 
     override fun onBindViewHolder(holder: RecyclerView.ViewHolder, position: Int) {
-        val (status, color, isChecked) = statusList?.get(position)!!
+        var (status, color, isChecked) = statusList?.get(position)!!
         val states = arrayOf(intArrayOf(android.R.attr.state_checked), intArrayOf())
         val colors = intArrayOf(color, color)
         (holder as ViewHolder).cbStatusSelect?.isChecked = isChecked
+        holder.cbStatusSelect!!.setOnClickListener{
```
Comment (jawidMuhammadi) [inline app/src/main/java/org/mifos/mobile/ui/adapters/CheckBoxAdapter.kt]: The assertion operator `(!!)` throws a null pointer exception if `cbStatusSelect` is null, would be better if you use the safeCall operator `(?.)`

**Review by jawidMuhammadi — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobile/ui/adapters/CheckBoxAdapter.kt (hunk 1 above)
Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/adapters/CheckBoxAdapter.kt]: I have done the changes ,sir
