### PR TITLE
Fix #793 : Resolved Nav Drawer selected item on Logout

### LINKED ISSUE #793: Nav Drawer selected item on Logout cancelling
**Summary:**

Nav Drawer selected item on Logout cancelling

**Steps to reproduce:**

1) Open Nav Drawer
2) Click Logout
3) Then, Cancel logout

**Expected behaviour:**

Nav Drawer selected item should be at Home

**Observed behaviour:**

Instead, it's on Logout which causes inconsistency in Nav Drawer and Home Activity

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

issue_nav_drawer_logout

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #793 

pr_nav_logout

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@therajanmaurya @dilpreet96 @satyan @droidchef Please review this PR.

File: app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java [hunk 1]
```diff
@@ -138,6 +138,7 @@ protected void onPause() {
 
     @Override
     protected void onResume() {
+
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/ui/activities/HomeActivity.java]: Please remove this line
