### PR TITLE
fix: Issue #447 - Display Currency Code if Currency Symbol is NULL

### LINKED ISSUE #447: Currency symbol displayed as null
**Summary:**

Currency symbol is displayed as null in Charges screen.

**Steps to reproduce:**

Open the charges tab.

**Expected behavior:**

It should have the appropriate currency sign.

**Observed behavior:**

null is displayed instead of the currency sign.

**Device and Android version:**

Samsung A5(2016)

**Screenshots:**

image

### PR DESCRIPTION
**Pull request by luckyman20**
Fixes #447 
@therajanmaurya @santoshmath Please review it!!

### CODE REVIEW

File: app/src/main/java/org/mifos/mobilebanking/models/Currency.java [hunk 1]
```diff
@@ -40,6 +40,9 @@ public void setDecimalPlaces(int decimalPlaces) {
     }
 
     public String getDisplaySymbol() {
+        if (displaySymbol == null) {
+            displaySymbol = getCode();
+        }
```
Comment (therajanmaurya) [inline app/src/main/java/org/mifos/mobilebanking/models/Currency.java]: @luckyman20 PR looks good, I want a small change 
```
 public String getDisplaySymbol() {
        if(displaySymbol == null) {
            return code;
        }
        return displaySymbol;
    }
```

**Review by therajanmaurya — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobilebanking/models/Currency.java (hunk 1 above)
Comment (luckyman20) [reply app/src/main/java/org/mifos/mobilebanking/models/Currency.java]: @therajanmaurya Made the changes

**Review by therajanmaurya — APPROVED** [review]
