### PR TITLE
fix: app crashes when selecting an empty Product ID

### LINKED ISSUE #1897: App Crashes when clicking on submit button without selecting product ID
**Summary:**

App crashes when u click on submit button in Apply Savings Account

**Steps to reproduce:**

https://user-images.githubusercontent.com/90026952/216305746-2822b26f-270e-4fa2-9060-20ecfcb15121.mp4

**Expected behaviour:**

An appropriate message stating "Product ID cannot be null" or something similar should be displayed

**Device and Android version:**

Device: Samsung M11
Android: 11

### PR DESCRIPTION
**Pull request by PratyushSingh07**
Fixes #1897

https://user-images.githubusercontent.com/90026952/216330636-02357428-941a-4878-a01b-7fcb48014da1.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Review by IOhacker — APPROVED** [review]

**Comment by PratyushSingh07** [comment]
@IOhacker com.github.Raizlabs.DBFlow:dbflow-core:4.1.2. needs to be upgraded to 4.2.4

File: app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt [hunk 1]
```diff
@@ -122,7 +122,11 @@ class SavingsAccountApplicationFragment : BaseFragment(), SavingsAccountApplicat
     private fun submitSavingsAccountApplication() {
         val payload = SavingsAccountApplicationPayload()
         payload.clientId = template?.clientId
+        if(productIdList.indexOf(productIdField!!.text.toString())!=-1)
         payload.productId = productIdList.indexOf(productIdField!!.text.toString()).let { productOptions?.get(it)?.id }
+        else {
+            Toast.makeText(activity,"Select a Product Id",Toast.LENGTH_SHORT).show()
```
Comment (rahul-gill) [inline app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt]: - Use string resources instead of hard-coded string
- Method should return immediately after showing the toast
- combine the two commits into a single one

Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt]: @rahul-gill i will use the string resource but can you help me out with the 2nd point of yours, I don't think I exactly know what you mean

Comment (rahul-gill) [reply app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt]: There's no use executing code after line 129 if the product id is not selected, so the function should return after showing the toast.

Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt]: @i think i got your point, also can i push the upgraded version of com.github.Raizlabs.DBFlow:dbflow-core:4.1.2. in the next commit ?

Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt]: > @i think i got your point, also can i push the upgraded version of com.github.Raizlabs.DBFlow:dbflow-core:4.1.2. in the next commit ?

@rahul-gill

Comment (rahul-gill) [reply app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt]: 👍

**Comment by PratyushSingh07** [comment]
@rahul-gill @IOhacker kindly review the changes in this PR

File: app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt [hunk 2]
```diff
@@ -122,7 +122,12 @@ class SavingsAccountApplicationFragment : BaseFragment(), SavingsAccountApplicat
     private fun submitSavingsAccountApplication() {
         val payload = SavingsAccountApplicationPayload()
         payload.clientId = template?.clientId
+        if(productIdList.indexOf(productIdField!!.text.toString())!=-1)
```
Comment (jawidMuhammadi) [inline app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt]: - Use safe call operator `(?.)`
- Add brackets for `if`
- Add space between ` != ` and` -1` ( Or just press CTRL+ALT+L on Windows or Command+Option+L on Mac. The android studio will reformat all the code for you. I would recommend following this best practice in your daily coding)

Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/fragments/SavingsAccountApplicationFragment.kt]: @jawidMuhammadi i have done the changes, kindly review them

**Comment by jawidMuhammadi** [comment]
Why CI is failing? Update the title, please

**Comment by PratyushSingh07** [comment]
will fix them @jawidMuhammadi , I will either open a new PR for this and close this one or will try to fix this itself.
I will fix all of my PRs that haven't been merged in the next 2 3 days

**Comment by PratyushSingh07** [comment]
i have fixed this PR @jawidMuhammadi , Kindly review this

**Comment by PratyushSingh07** [comment]
@jawidMuhammadi fixed this long pending PR ,kindly have a look

**Review by jawidMuhammadi — CHANGES_REQUESTED** [review]
Squash your commits, please

**Comment by PratyushSingh07** [comment]
squashed the commits @jawidMuhammadi , kindly have a look

**Review by jawidMuhammadi — APPROVED** [review]
Looks good to me!
