### PR TITLE
Fix#2356 Guarantor Type Selection Fixed

### LINKED ISSUE #2356: App crashes when selecting Guarantor Type
**Summary:**

App crashes when we try to add a guarantor 

**Steps to reproduce:**

- Go to Accounts
- Switch over to Loan Section
- Click on a loan to move to Loan Account Details
- Click on 3 vertical dots & then click on View Guarantor
- Try adding a guarantor with type either `choicea` or `choiceB`

**Expected behaviour:**

Guarantor should have been added with the specified details

**Observed behaviour:**

Guarantor isnt added and we move out of the guarantor screen
## This is to be noted that this behaviour is observed only when I choose either  `choicea` or `choiceB` . It works perfectly for rest of the `Gurantor Type`

https://github.com/openMF/mifos-mobile/assets/90026952/4bb4aebc-d899-4f6d-a9f5-1561f822f427

**Device and Android version:**

Device: Pixel 7
Android: 13

### PR DESCRIPTION
**Pull request by SekhGulamMainuddin**
Fixes #2356 

Removed the **choicea** and **choiceB** Options since they had no usage and were added explicitly in the code. Currently it has three Guarantor Type i.e. **CUSTOMER**, **STAFF** and **EXTERNAL**

Please add #hacktoberfest on merge.

https://github.com/openMF/mifos-mobile/assets/73953395/2b3bf339-3a0d-4b84-bc45-0c011b81d2aa

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
Add a screen recording, screenshot wont be helpful in this case

**Comment by SekhGulamMainuddin** [comment]
@therajanmaurya please merge my PR.
Please add hacktoberfest tags on merge.

**Comment by SekhGulamMainuddin** [comment]
> Add a screen recording, screenshot wont be helpful in this case

added

**Comment by SekhGulamMainuddin** [comment]
@therajanmaurya please merge my PR.
Please add **hacktoberfest** tags on merge.

**Comment by SekhGulamMainuddin** [comment]
@PratyushSingh07 can you please review this PR

**Comment by SekhGulamMainuddin** [comment]
@PratyushSingh07 please review this PR

File: app/src/main/java/org/mifos/mobile/ui/fragments/AddGuarantorFragment.kt [hunk 1]
```diff
@@ -39,20 +40,27 @@ class AddGuarantorFragment : BaseFragment() {
...
-    var index: Int? = 0
+    private var index: Int? = 0
     override fun onCreate(savedInstanceState: Bundle?) {
         super.onCreate(savedInstanceState)
         if (arguments != null) {
             loanId = arguments?.getLong(Constants.LOAN_ID)
-            guarantorState = requireArguments()
-                .getSerializable(Constants.GUARANTOR_STATE) as GuarantorState
-            payload = arguments?.getParcelable(Constants.PAYLOAD)
+            guarantorState = if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.TIRAMISU) {
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/fragments/AddGuarantorFragment.kt:54]: is it necessary to check the Build version ?

**Review by PratyushSingh07 — CHANGES_REQUESTED** [review]
please format your code , you can use ctrl+alt+L if you are on windows

File: app/src/main/java/org/mifos/mobile/ui/fragments/AddGuarantorFragment.kt (hunk 1 above)
Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/ui/fragments/AddGuarantorFragment.kt:54]: > is it necessary to check the Build version ?

Yes because the min SDK version is 22 and the above code is deprecated for newer Android api versions so I added a check.

Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/ui/fragments/AddGuarantorFragment.kt:54]: > is it necessary to check the Build version ?


Yes because the min SDK version is 22 and the above code is deprecated for newer Android api versions i.e. Android Tiramisu onwards, so I added a check.

Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/ui/fragments/AddGuarantorFragment.kt:54]: @PratyushSingh07 I have added the changes of formatting the code.

**Comment by SekhGulamMainuddin** [comment]
@PratyushSingh07 I have added the changes of formatting the code. Please review it.

**Comment by PratyushSingh07** [comment]
LGTM @therajanmaurya , we can merge this
