### PR TITLE
Fix:Wrong parcelable impl. of Client model

### LINKED ISSUE #1826: Apply For Loan option terminating with error
@rrpawar96  The error below is noticed and application terminates on the **Apply For Loan** function :

Selecting this option and waiting for a few seconds when the option screen is displayed results in the status in the image below:

image

I/MultiDex: VM has multidex support, MultiDex support library is disabled.
W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.mifos.mobile, PID: 26240
    java.lang.RuntimeException: Unable to start activity ComponentInfo{org.mifos.mobile/org.mifos.mobile.ui.activities.HomeActivity}: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class org.mifos.mobile.models.client.Client
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
        at android.app.ActivityThread.-wrap11(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5417)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class org.mifos.mobile.models.client.Client
        at android.os.Parcel.readParcelableCreator(Parcel.java:2415)
        at android.os.Parcel.readParcelable(Parcel.java:2337)
        at android.os.Parcel.readValue(Parcel.java:2243)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:2592)
        at android.os.BaseBundle.unparcel(BaseBundle.java:221)
        at android.os.BaseBundle.getInt(BaseBundle.java:795)
        at androidx.appcompat.app.AppCompatDelegateImpl.onCreate(AppCompatDelegateImpl.java:291)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:73)
        at org.mifos.mobile.ui.activities.HomeActivity.onCreate(HomeActivity.kt:73)
        at android.app.Activity.performCreate(Activity.java:6237)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
        at android.app.ActivityThread.-wrap11(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:148) 
        at android.app.ActivityThread.main(ActivityThread.java:5417) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

### PR DESCRIPTION
**Pull request by rahul-gill**
Fixes #1826

### CODE REVIEW

File: app/src/main/java/org/mifos/mobile/models/client/Client.kt [hunk 1]
```diff
@@ -1,132 +1,60 @@
...
+    var accountNo: String? = null,
 
-    private var status: Status? = null
+    private var status: Status? = null,
 
-    private var active: Boolean? = null
+    private var active: Boolean? = null,
 
-    var activationDate: List<Int?>? = ArrayList()
+    var activationDate: List<Int?>? = ArrayList(),
```
Comment (devansh-299) [inline app/src/main/java/org/mifos/mobile/models/client/Client.kt]: No need for allowing nullable in the list. Also since you are setting the default value as an empty ArrayList, no need for allowing nullable as `activationDate` value

File: app/src/main/java/org/mifos/mobile/models/client/Client.kt [hunk 2]
```diff
@@ -1,132 +1,60 @@
...
 
-    var dobDate: List<Int?> = ArrayList()
+    var dobDate: List<Int?> = ArrayList(),
```
Comment (devansh-299) [inline app/src/main/java/org/mifos/mobile/models/client/Client.kt]: same here

**Review by devansh-299 — CHANGES_REQUESTED** [review]
Also @rahul-gill you have a few changes which are not related to this pull request. Please revert them, rest of the changes are fine

**Comment by rahul-gill** [comment]
> Also @rahul-gill you have a few changes which are not related to this pull request. Please revert them, rest of the changes are fine

Done

**Review by devansh-299 — APPROVED** [review]
