### PR TITLE
Fix: #1678 Fixed Loan Amount showing in Exponential Form Issue

### LINKED ISSUE #1678: Amount column in LOAN fragment must not be in exponential form
**Summary:**
Amount column in LOAN fragment must not be in exponential form for bigger amount

**Steps to reproduce:**
1. Open Apply for Loan fragment
2. Select a product whose initial principal amount is large, for eg. 'Tranche Loan Product'
3. Observe

**Expected behaviour:**
Principal Amount must be shown in numeric format

**Observed behaviour:**
Principal Amount is shown in exponential format

**Device and Android version:**
OnePlus 6
Android 10

**Screenshots:**

WhatsApp Image 2021-01-07 at 12 09 48 AM

WhatsApp Image 2021-01-07 at 12 16 23 PM

### PR DESCRIPTION
**Pull request by SekhGulamMainuddin**
Fixes #1678 

Fixed the Loan Amount showing Exponential Form for larger principal amount

[Fixed Loan Amount showing in Exponential Form Issue.webm](https://github.com/openMF/mifos-mobile/assets/73953395/31706481-46b5-4617-8cd3-29c7baf58040)

### CODE REVIEW

**Comment by SekhGulamMainuddin** [comment]
Hi @PratyushSingh07 can you please review this PR

File: app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt [hunk 1]
```diff
@@ -83,16 +71,14 @@ class ReviewLoanApplicationFragment : BaseFragment() {
         }
     }
 
-
-    private lateinit var viewModel: ReviewLoanApplicationViewModel
+    private val viewModel by activityViewModels<ReviewLoanApplicationViewModel>()
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt]: use this `private val viewModel: ReviewLoanApplicationViewModel by viewModels()` as we are working with single fragment and we need viewmodel scoped to this fragment. We can use your declaration when you want to share ViewModel between fragments within the same activity.

File: app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt [hunk 2]
```diff
@@ -115,38 +101,43 @@ class ReviewLoanApplicationFragment : BaseFragment() {
...
+            tvNewLoanApplication.text = viewModel.getLoanName()
+            tvAccountNumber.text = viewModel.getAccountNo()
+
+            btnLoanSubmit.setOnClickListener {
+                showProgress()
+                viewModel.submitLoan()
+                    ?.observeOn(AndroidSchedulers.mainThread())
+                    ?.subscribeOn(Schedulers.io())
+                    ?.subscribeWith(object : DisposableObserver<ResponseBody>() {
+                        override fun onComplete() {
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt]: this piece of code should not have been here. Move this to viewmodel and while doing so make sure to use coroutines instead of RxJava

**Review by PratyushSingh07 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt (hunk 1 above)
Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt]: Yes now I changed it to `private val viewModel by viewModels<ReviewLoanApplicationViewModel>()`.

File: app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt (hunk 2 above)
Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt]: I have changed it to Livedata and Coroutines as you said. Please review it.

File: app/src/main/java/org/mifos/mobile/utils/SubmitLoanUiState.kt [hunk 3]
```diff
@@ -0,0 +1,10 @@
+package org.mifos.mobile.utils
+
+import okhttp3.ResponseBody
+
+sealed class SubmitLoanUiState {
+    object Loading : SubmitLoanUiState()
+    data class Next(val responseBody: ResponseBody) : SubmitLoanUiState()
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/utils/SubmitLoanUiState.kt]: name of data class should be self explanatory , `Next` doesnt imply much

File: app/src/main/java/org/mifos/mobile/viewModels/ReviewLoanApplicationViewModel.kt [hunk 4]
```diff
@@ -63,14 +67,24 @@ class ReviewLoanApplicationViewModel @Inject constructor(var dataManager: DataMa
 
     fun getLoanState() = loanState
 
-    fun submitLoan(): Observable<ResponseBody?>? {
+    private val _submitLoanUiState = MutableLiveData<SubmitLoanUiState>()
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/viewModels/ReviewLoanApplicationViewModel.kt]: use state flow instead of live data and then make necessary changes in the fragment

File: app/src/main/java/org/mifos/mobile/viewModels/ReviewLoanApplicationViewModel.kt [hunk 5]
```diff
@@ -63,14 +67,24 @@ class ReviewLoanApplicationViewModel @Inject constructor(var dataManager: DataMa
...
         loansPayload.currency = null
-        return if (loanState == LoanState.CREATE) {
-            dataManager?.createLoansAccount(loansPayload)
-        } else {
-            dataManager?.updateLoanAccount(loanId, loansPayload)
+
+        _submitLoanUiState.postValue(SubmitLoanUiState.Loading)
+        try {
+            val response = if (loanState == LoanState.CREATE) {
+                dataManager?.createLoansAccount(loansPayload)
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/viewModels/ReviewLoanApplicationViewModel.kt]: viewmodel should take data from the repository and not directly from the source. Make an interface by the name of `ReviewLoanApplicationRepository` and then implement this interface in a class that you can call as `ReviewLoanApplicationRepositoryImp`  .  You can take reference from the code that we wrote during GSoC.

File: app/src/main/java/org/mifos/mobile/utils/SubmitLoanUiState.kt [hunk 6]
```diff
@@ -0,0 +1,10 @@
+package org.mifos.mobile.utils
+
+import okhttp3.ResponseBody
+
+sealed class SubmitLoanUiState {
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/utils/SubmitLoanUiState.kt]: change the name to `ReviewLoanApplicationUiState`

File: app/src/main/java/org/mifos/mobile/viewModels/ReviewLoanApplicationViewModel.kt [hunk 7]
```diff
@@ -63,14 +67,24 @@ class ReviewLoanApplicationViewModel @Inject constructor(var dataManager: DataMa
...
+            } else {
+                dataManager?.updateLoanAccount(loanId, loansPayload)
+            }
+            _submitLoanUiState.postValue(SubmitLoanUiState.Next(response!!))
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/viewModels/ReviewLoanApplicationViewModel.kt]: When you use StateFlow you wont be using postValue because there is no set nor post. It’s just the stateFlow.value.
There is a difference between postValue and value when using LiveData , you can read it from the internet  (this is just fyi , thought to share it with you)

**Review by PratyushSingh07 — CHANGES_REQUESTED** [review]

**Comment by PratyushSingh07** [comment]
Also @SekhGulamMainuddin please do not resolve conversation on your own . Let the reviewer do it please

**Comment by SekhGulamMainuddin** [comment]
Ok I'll make the changes

**Comment by SekhGulamMainuddin** [comment]
@PratyushSingh07 I have made the changes as you said. Please review it.

File: app/src/main/java/org/mifos/mobile/repositories/ReviewLoanApplicationRepository.kt [hunk 8]
```diff
@@ -0,0 +1,45 @@
...
+
+    fun getDisbursementDate() : String?
+
+    fun getLoanName() : String
+
+    fun getAccountNo() : String
+
+    fun getLoanState() : LoanState
+
+    suspend fun submitLoan(): Flow<ResponseBody>
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/repositories/ReviewLoanApplicationRepository.kt]: we need only this in our repository , I dont think we need rest of the functions that you have defined above. Any module should follow SRP i.e Single Responsibility Principle

File: app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt [hunk 9]
```diff
@@ -115,53 +100,67 @@ class ReviewLoanApplicationFragment : BaseFragment() {
...
+                viewModel.submitLoan()
+            }
 
-                    override fun onNext(t: ResponseBody) {
-                        hideProgress()
-                        if (viewModel.getLoanState() == LoanState.CREATE) {
-                            showLoanAccountCreatedSuccessfully()
-                        } else {
-                            showLoanAccountUpdatedSuccessfully()
+            viewLifecycleOwner.lifecycleScope.launch {
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt:122]: There is a safer to way collect flows . You can read this from [here](https://medium.com/androiddevelopers/a-safer-way-to-collect-flows-from-android-uis-23080b1f8bda#:~:text=If%20you're%20building%20an,in%20a%20lifecycle%2Daware%20manner) & then make necessary changes afterward

File: app/src/main/java/org/mifos/mobile/utils/ReviewLoanApplicationUiState.kt [hunk 10]
```diff
@@ -0,0 +1,11 @@
+package org.mifos.mobile.utils
+
+import okhttp3.ResponseBody
+
+sealed class ReviewLoanApplicationUiState {
+    object Initial : ReviewLoanApplicationUiState()
+    object Loading : ReviewLoanApplicationUiState()
+    data class ReviewSuccess(val responseBody: ResponseBody) : ReviewLoanApplicationUiState()
+    data class Error(val throwable: Throwable) : ReviewLoanApplicationUiState()
+
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/utils/ReviewLoanApplicationUiState.kt]: remove whitespaces

**Review by PratyushSingh07 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobile/repositories/ReviewLoanApplicationRepository.kt (hunk 8 above)
Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/repositories/ReviewLoanApplicationRepository.kt]: Actually, I was doing the same but inside the submit loan function some variables were required which is the reason I moved all of them to the repository. 

```
override suspend fun submitLoan(): Flow<ResponseBody> {
        loansPayload.productName = null
        loansPayload.loanPurpose = null
        loansPayload.currency = null

        return flow {
            emit(
                if (loanState == LoanState.CREATE) {
                    dataManager.createLoansAccount(loansPayload)
                } else {
                    dataManager.updateLoanAccount(loanId, loansPayload)
                }
            )
        }
    }
```

File: app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt (hunk 9 above)
Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt:122]: Changing it

File: app/src/main/java/org/mifos/mobile/utils/ReviewLoanApplicationUiState.kt (hunk 10 above)
Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/utils/ReviewLoanApplicationUiState.kt]: Ok, I am removing the white spaces.

File: app/src/main/java/org/mifos/mobile/repositories/ReviewLoanApplicationRepository.kt (hunk 8 above)
Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/repositories/ReviewLoanApplicationRepository.kt]: Ok then I am passing the loansPayload, loanState and loanId as parameters to the submitLoan function

File: app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt (hunk 9 above)
Comment (SekhGulamMainuddin) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ReviewLoanApplicationFragment.kt:122]: I added this with ` repeatOnLifecycle(Lifecycle.State.STARTED) {} `

**Comment by PratyushSingh07** [comment]
LGTM to @SekhGulamMainuddin , great job. We can merge this PR @therajanmaurya
