### PR TITLE
fix: Issue #453 - Cancel button working in Third Party Transfer

### LINKED ISSUE #453: Cancel Button is not working in "third party transfer".
**Summary:**

Cancel button is not working in "Third Party transfer" section .

**Steps to reproduce:**
Go to navigation Transfer->Third Party Transfer .Fill the details and click on cancel .

**Expected behavior:**
On clicking on cancel it should cancel the transfer and finish the activity .

**Observed behavior:**

On clicking on cancel .Nothing was happening .

**Device and Android version:**
Moto G3 (6.0.1) 

I would like to work on this issue .

### PR DESCRIPTION
**Pull request by luckyman20**
Fixes #453

@dilpreet96 @Anh3h Please review it !!

### CODE REVIEW

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/ThirdPartyTransferFragment.java [hunk 1]
```diff
@@ -94,6 +94,7 @@
     @BindView(R.id.tv_enter_remark)
     TextView tvEnterRemark;
 
+
```
Comment (dilpreet2028) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/ThirdPartyTransferFragment.java]: Remove this extra space

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/ThirdPartyTransferFragment.java [hunk 2]
```diff
@@ -329,6 +330,12 @@ public void amountSet() {
         etAmount.setEnabled(false);
     }
 
+    @OnClick(R.id.btn_cancel_transfer)
+    public void cancelTransfer() {
+        getActivity().getSupportFragmentManager().popBackStack();
+    }
+
+
```
Comment (dilpreet2028) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/ThirdPartyTransferFragment.java]: Remove this extra space too

**Review by dilpreet2028 — CHANGES_REQUESTED** [review]

**Comment by luckyman20** [comment]
@dilpreet96 Made the Changes

**Review by dilpreet2028 — APPROVED** [review]
