### PR TITLE
fix: Add check for null pointer exception on transaction list in savi…

### LINKED ISSUE #979: App crashes on clicking transaction in closed saving account.
**Summary:**

When the user clicks on "Transactions" in the closed saving account details, app crashes.

**Steps to reproduce:**

1.) Go to the accounts tab.
2.) Then select the closed account 000000031.
3.) Then click on "Transactions".

**Expected behaviour:**

If the transaction list is empty, it should display "No recent transactions".

**Observed behaviour:**

As I clicked on "Transaction", it opened "SavingAccountTransactionFragment" and then the app crashed. 

**Device and Android version:**

Xiaomi Redmi Note 3
Android 6.0.1, API 23

**Screenshots:**

screenshot_2019-01-13-15-30-14-452_org mifos mobilebanking

### PR DESCRIPTION
**Pull request by jsuyash1514**
Fixes #979 

This PR adds a check if transaction list is null or not.

Please Add Screenshots If there are any UI changes.

img_20190113_232212

@luckyman20 While building this project for the first time, I got an error `No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android` :- 

screenshot_20190113_194448

On googling this error, I found its solution which is to upgrade the dependency level of `com.android.tools.build:gradle` in the project level gradle from `3.0.0` to `3.2.1`

I've made the necessary changes. Please have a look.

### CODE REVIEW

**Comment by jsuyash1514** [comment]
It looks like Travis build failed due to the gradle changes. 
How should I solve this gradle build error `No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android` then?
@luckyman20  @therajanmaurya

**Comment by luckyman20** [comment]
Uninstall NDK, that's what worked for me.

**Comment by jsuyash1514** [comment]
@luckyman20 
Yeah, that worked for me too. I've undone all the gradle changes and squashed the commits into a single commit. Kindly review it.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java [hunk 1]
```diff
@@ -160,7 +160,7 @@ public void showSavingAccountsDetail(SavingsWithAssociations
         this.savingsWithAssociations = savingsWithAssociations;
         transactionsList = savingsWithAssociations.getTransactions();
 
-        if (transactionsList.size() > 0) {
+        if (transactionsList != null && transactionsList.size() > 0) {
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java]:
```suggestion
        if (transactionsList != null && !transactionsList.isEmpty()) {
```

**Review by luckyman20 — COMMENTED** [review]
Please make the required changes. It is always better and recommended to use the core functions doing same thing because they might contain some other checks too which might be helpful to us.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java (hunk 1 above)
Comment (jsuyash1514) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java]: Okay @luckyman20, I'll take care of it from next time. I've made the requested changes. Please have a look.

**Review by luckyman20 — APPROVED** [review]
Looks good.

**Comment by jsuyash1514** [comment]
@miPlodder I've made all the necessary changes. Please review.

**Comment by jsuyash1514** [comment]
@miPlodder @therajanmaurya I've made all the necessary changes. Kindly review.
