### PR TITLE
Fix #899: Replaced Snackbar with Toast in Recent Transactions

### LINKED ISSUE #899: Recent Transaction Fragment shows Snackbar every time on opening
**Summary:**

Recent Transaction Fragment shows Snackbar every time on opening

**Steps to reproduce:**

Go to Navigation Drawer > Recent Tranactions

**Expected behaviour:**

Snackbar should not pop up everytime. (no need to show the snackbar)

**Observed behaviour:**

Instead, it pops up everytime

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

### PR DESCRIPTION
**Pull request by migueldinisdev**
Fixes #899 

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

Squashed them into 1 commit.

image

Awaiting response.

### CODE REVIEW

**Comment by migueldinisdev** [comment]
Bot is failing and I cannot see why. The lines of code which were changed are only a few and do not interfere with Gradle settings or other stuff. It compiles in my computer, though.

**Comment by migueldinisdev** [comment]
Realized the error comes from this: https://github.com/openMF/mifos-mobile/commit/aa20e9f1a30bf951a6aebfeca1e5dd0b13380ee9

This commit had a build failed for the same reason mine had. Don't know whats going on and I cannot fix it.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/RecentTransactionsFragment.java [hunk 1]
```diff
@@ -147,9 +147,14 @@ public void onRefresh() {
...
     }
 
+    /**
+     * Shows a Toast
+     * @param message
+     */
     @Override
     public void showMessage(String message) {
-        Toaster.show(rootView, message, Toaster.LONG);
+        //Toaster.show(rootView, message, Toaster.LONG);
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/RecentTransactionsFragment.java]: Remove this comment.

**Review by miPlodder — CHANGES_REQUESTED** [review]

**Comment by migueldinisdev** [comment]
@miPlodder Done. Perhaps should I squash the 2 commits...

**Comment by miPlodder** [comment]
@MigDinny Development branch Build is passing.

Run `gradlew build` command or `./gradlew build` on the Studio and fix the build. Try to research properly and solve the issue properly before pinging me. (don't worry about the deadline)

**Comment by migueldinisdev** [comment]
@miPlodder Solved the problem. I had to remove an unused import. It's building now :)

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/RecentTransactionsFragment.java (hunk 1 above)
Comment (migueldinisdev) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/RecentTransactionsFragment.java]: Done

**Comment by luckyman20** [comment]
@MigDinny Please follow the commit guidelines - https://github.com/openMF/mifos-mobile/wiki/Commit-Style-Guide

Also, you replaced Snackbar with Toast which is not required. You have to ensure that snackbar doesn't popup on opening this screen. Please fix that.

**Comment by miPlodder** [comment]
@luckyman20 Actually, I asked him to add Toast instead of removing Snackbar. Actually, we are using Pagination there. So, it will be better to have a Toast instead of Snackbar. It gives the whole thing a better experience while scrolling.

**Comment by migueldinisdev** [comment]
I changed the commit message. Check it out!

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/RecentTransactionsFragment.java [hunk 2]
```diff
@@ -147,9 +146,13 @@ public void onRefresh() {
         recentTransactionsPresenter.loadRecentTransactions(false, 0);
     }
 
+    /**
+     * Shows a Toast
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/RecentTransactionsFragment.java]: Change this to 'Shows a Toast when no more Recent Transactions are available

Comment (miPlodder) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/RecentTransactionsFragment.java]: @luckyman20 I don't think this is required is required. Since it's a generic method. We can call it anywhere to show a message.

Comment (luckyman20) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/RecentTransactionsFragment.java]: @miPlodder Ahh.. I see.

**Review by miPlodder — APPROVED** [review]
