### PR TITLE
fix:scrollable filters in landscape mode

### LINKED ISSUE #1980: Filters aren't scrollable in landscape mode
**Summary:**

- When the orientation of the app is changed to landscape mode the filters are no longer scrollable making it difficult for users to check the desired fields
- This issue is persistent even after changing the tabs to `Loan` and `Share`

**Steps to reproduce:**
- open the app
- click on accounts in the home section of the app
- in the top right corner , click on filters and then change the orientation

**Expected behaviour:**

The filters should have been scrollable even in the landscape mode

**Observed behaviour:**
- This is what you pretty much find if the orientation is changed to landscape
WhatsApp Image 2023-03-14 at 20 38 54

**Device and Android version:**

Device : Samsung M11
Android : 11

### PR DESCRIPTION
**Pull request by PratyushSingh07**
Fixes #1980

https://user-images.githubusercontent.com/90026952/225119065-deea8762-e821-4f03-8b64-d003d9aa023b.mp4

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PratyushSingh07** [comment]
@jawidMuhammadi could you please review this

File: app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt [hunk 1]
```diff
@@ -339,6 +328,9 @@ import javax.inject.Inject
                     checkBoxAdapter?.statusList = (childFragmentManager
                             .findFragmentByTag(getFragmentTag(0)) as AccountsFragment?)?.getCurrentFilterList()
                 }
+                if(resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE){
+                    checkBoxRecyclerView!!.layoutParams.height = (getScreenHeight()/3.5).toInt()
+                }
```
Comment (jawidMuhammadi) [inline app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt]: Is there any reason why you have copy pasted the same part of the code in 3 different places, what about if you remove this part of the code from the `when` block and maybe put it under line number 321? This way, you won't need to replicate it.

File: app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt [hunk 2]
```diff
@@ -359,6 +354,9 @@ import javax.inject.Inject
                     checkBoxAdapter?.statusList = (childFragmentManager
                             .findFragmentByTag(getFragmentTag(2)) as AccountsFragment?)?.getCurrentFilterList()
                 }
+                if(resources.configuration.orientation == Configuration.ORIENTATION_LANDSCAPE){
+                    checkBoxRecyclerView!!.layoutParams.height = (getScreenHeight()/3.5).toInt()
```
Comment (jawidMuhammadi) [inline app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt]: Why divide by 3.5, could you please clarify?

**Review by jawidMuhammadi — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt (hunk 2 above)
Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt]: 3.5 was need to adjust the size of the checkbox in landscape mode . This was tested on 3 devices 
- Samsung M11
- One plus nord 2
- Redmi note 9

File: app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt (hunk 1 above)
Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt]: You are right, we can write that at 321 and the if condition would be checked once but even if we write it 3 times even in this case the if condition would be executed once because at a time only one of the three account types would be clicked. 
Having said that , I can fix this and push it in the next commit if you would say so

Comment (jawidMuhammadi) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt]: Yeah, let's do that to avoid cod redundancy :)

Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt]: done !!

Comment (jawidMuhammadi) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt]: And the last change, can we use `?.` safe call operator instead of `!!`?

Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/ui/fragments/ClientAccountsFragment.kt]: done @jawidMuhammadi

**Review by jawidMuhammadi — APPROVED** [review]
Good Job! @PratyushSingh07
