### PR TITLE
[2656] - refactor: Recent transactions from XML to compose

### LINKED ISSUE #2469: refactor: Migrate RecentTransaction to compose
**Summary:**

No error Ui in recent transaction when the app is deprived of internet connection. 

**Steps to reproduce:**

Switch of the internet and head over to the recent transaction

**Expected behaviour:**

Error UI in case of no internet just like we have in other screens

**Observed behaviour:**

Blank screen

**Device and Android version:**

Device: Pixel 7
Android: 14

**Screenshots:**
recent transaction

### PR DESCRIPTION
**Pull request by akashmeruva9**
Fixes #2469

<table style="border: 1px solid black;">
            <tr>
                <td  style="border: 1px solid black ;">
                    
                </td>
                <td  style="border: 1px solid black ;">
                    
                </td>
                <td  style="border: 1px solid black ;">
                    
                </td>
            </tr>
</table>

<table style="border: 1px solid black;">
            <tr>
                <td  style="border: 1px solid black ;">
                    
            </tr>
</table>

https://github.com/openMF/mifos-mobile/assets/106223361/0618c246-2364-4f80-a675-9d6fe71144bb

Please make sure these boxes are checked before submitting your pull request - thanks!

- [ x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [ ] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [ x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionViewModel.kt [hunk 1]
```diff
@@ -1,4 +1,4 @@
-package org.mifos.mobile.viewModels
+package org.mifos.mobile.ui.recent_transactions
```
Comment (AdityaKumdale) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionViewModel.kt:2]: create a bool mutable stateflow for refreshing the screen in viewmodel , create a function for it using launch which will set to false after fetching transactions

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 2]
```diff
@@ -0,0 +1,197 @@
...
+@Composable
+fun RecentTransactionScreen(
+    viewModel: RecentTransactionViewModel = hiltViewModel(),
+    navigateBack: () -> Unit )
+{
+    val uiState by viewModel.recentTransactionUiState.collectAsStateWithLifecycle()
+    LaunchedEffect(key1 = Unit) {
+        viewModel.loadRecentTransactions(false, 0)
+    }
+
```
Comment (AdityaKumdale) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt:69]: collect the refresh state here, pass it in screen whereever you need it,
then you can use 'PullRefreshIndicator' in your composable

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 3]
```diff
@@ -0,0 +1,197 @@
...
+    RecentTransactionScreen(
```
Comment (AdityaKumdale) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt:70]: create a callback for refresh function in viewmodal and pass it down the composable hierarchy whereever you need it

**Review by AdityaKumdale — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 4]
```diff
@@ -0,0 +1,237 @@
...
+@Composable
+fun RecentTransactionScreenContent(
+    uiState: RecentTransactionUiState,
+    navigateBack: () -> Unit,
+    retryConnection: () -> Unit,
+    isRefreshing: Boolean,
+    onRefresh: () -> Unit) {
+
+    val context = LocalContext.current
+    val pullRefreshState = rememberPullToRefreshState()
```
Comment (AdityaKumdale) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt:93]: pass isRefreshing and onRefresh in rememberPullToRefreshState

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 5]
```diff
@@ -0,0 +1,237 @@
...
+                }
+            }
+            LaunchedEffect(key1 = isRefreshing) {
+                if (isRefreshing)
+                    pullRefreshState.startRefresh()
+                else
+                    pullRefreshState.endRefresh()
+            }
+
+            PullToRefreshContainer(
```
Comment (AdityaKumdale) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt]: have you tried Indicator instead of Container

**Review by AdityaKumdale — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt (hunk 5 above)
Comment (akashmeruva9) [reply app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt]: The Indicator and Pasing isrefresh and refresh state insite pull refresh state is when we use modifier.pullrefresh() in material, but i am implementing it using nestedScrollConnection that is new pull refresh state on material 3 library

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt (hunk 4 above)
Comment (akashmeruva9) [reply app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt:93]: The problem is that th implemntation is good, but i don't know bcz of some UI overlap or something, when i swipe down my screen i can't see the progress bar, I have tried both pull refresh in material and nestedScrollConnection in material3

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 6]
```diff
@@ -0,0 +1,275 @@
...
+            RecentTransactionUiState.Initial
+        )
+}
+@Preview(showSystemUi = true, showBackground = true)
+@Composable
+private fun RecentTransactionScreenPreview(
+    @PreviewParameter(RecentTransactionScreenPreviewProvider::class) recentTransactionUiState: RecentTransactionUiState
+) {
+/*
+    MifosMobileTheme {
```
Comment (AdityaKumdale) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt:239]: Commented code ?

File: app/build.gradle.kts [hunk 7]
```diff
@@ -160,6 +160,9 @@ dependencies {
 
     implementation("com.github.rahul-gill.mifos-ui-library:uihouse:alpha-2.1")
 
+    //swipe to pull refresh
+    implementation ("androidx.compose:compose-bom:2024.05.00")
```
Comment (PratyushSingh07) [inline app/build.gradle.kts]: can we use version catalog ?

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionsFragment_Old.kt [hunk 8]
```diff
@@ -26,15 +26,14 @@ import org.mifos.mobile.ui.fragments.base.BaseFragment
...
-import org.mifos.mobile.viewModels.RecentTransactionViewModel
 import javax.inject.Inject
 
 /**
  * @author Vishwwajeet
  * @since 09/08/16
  */
 @AndroidEntryPoint
-class RecentTransactionsFragment : BaseFragment(), OnRefreshListener {
+class RecentTransactionsFragment_Old : BaseFragment(), OnRefreshListener {
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionsFragment_Old.kt]: any use of this fragment ?

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 9]
```diff
@@ -0,0 +1,275 @@
...
+
+                    is RecentTransactionUiState.LoadMoreRecentTransactions -> {
+                        LazyColumn(
+                            modifier = Modifier.fillMaxSize(),
+                            state = lazyColumnState
+                        ) {
+                            items(uiState.transactions) { transaction ->
+                                RecentTransactionListItem(transaction)
+                            }
+                        }
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt]: i dont think we need to another compose UI for this . The idea is to update the data source that is fetching all the recent transactions

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 10]
```diff
@@ -0,0 +1,275 @@
...
+                    }
+
+                    is RecentTransactionUiState.RecentTransactions -> {
+
+                        if (uiState.transactions?.isNotEmpty() == true) {
+                            LoadRecentTransactions(transactionList = uiState.transactions as ArrayList<Transaction>,lazyColumnState,uiState, viewModel)
+                        } else {
+                            MifosErrorComponent(isEmptyData = true)
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt]: if the list is empty then we can an Empty Data View instead of error component

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 11]
```diff
@@ -0,0 +1,275 @@
...
+}
+
+
+@Composable
+fun RecentTransactionListItem(transaction: Transaction?) {
+    Row(modifier = Modifier.padding(8.dp), verticalAlignment = Alignment.CenterVertically) {
+        Image(
+            painter = painterResource(id = R.drawable.ic_local_atm_black_24dp),
+            contentDescription = stringResource(id = R.string.atm_icon),
+            modifier = Modifier.size(39.dp)
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt]: will be better if we can use material guidelines. 39 dp doesn't make much sense .

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt (hunk 6 above)
Comment (akashmeruva9) [reply app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt:239]: that is for the preview, i should pass a view model io it, is there any way i can pass a dummy view model into it ??

**Review by PratyushSingh07 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt (hunk 6 above)
Comment (AdityaKumdale) [reply app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt:239]: No Akash passing a viewmodel to preview is a very bad Idea.Observe how we separate concerns in our prs it will give you idea.

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt [hunk 12]
```diff
@@ -0,0 +1,275 @@
...
+                            isNetworkConnected = Network.isConnected(context),
+                            isEmptyData = false,
+                            isRetryEnabled = true,
+                            onRetry = retryConnection
+                        )
+                    }
+
+                    RecentTransactionUiState.Initial -> {
+
+                    }
```
Comment (AvneetSingh2001) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt]: No need of Initial

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt (hunk 9 above)
Comment (AvneetSingh2001) [reply app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionScreen.kt]: appy pagingation: https://nameisjayant.medium.com/infinite-scrolling-with-paging-3-in-jetpack-compose-48c6593b4d35

File: app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionsFragment.kt [hunk 13]
```diff
@@ -0,0 +1,53 @@
...
+
+    override fun onCreateView(
+        inflater: LayoutInflater,
+        container: ViewGroup?,
+        savedInstanceState: Bundle?,
+    ): View {
+        setToolbarTitle(getString(R.string.recent_transactions))
+        return ComposeView(requireContext()).apply {
+            setContent {
+                MifosMobileTheme {
```
Comment (AvneetSingh2001) [inline app/src/main/java/org/mifos/mobile/ui/recent_transactions/RecentTransactionsFragment.kt]: use mifosComposeView

**Review by AvneetSingh2001 — CHANGES_REQUESTED** [review]
