### PR TITLE
fix : fixed the logic of comparator function that's used to sort notifications

### LINKED ISSUE #2000: In Utils the function that is used to compare notifications based on their timestamps is incorrect.
**Summary:**

In api -> local -> DatabaseHelper.kt, a comparator function utils -> NotificationComparator.kt -> compare() is used which is buggy and incorrect. 
In order to sort and store the notifications in descending order(based on their timestamp) a function compare is used which is incorrect and buggy(screenshot attached below)

**Steps to reproduce:**

How can we reproduce the issue?

check the function compare(in utils -> NotificationComparator.kt file)
attaching the screenshot below 

What did you expect the app to do?

comparator function should not have this bug, because due to this the working of notifications become prone to unintended errors.

What did you see instead?  Describe your issue in detail here.

Comparator function that's used to compare notifications has an error. 

What make and model device (e.g., Samsung Galaxy S3) did you encounter this on?  What Android
version (e.g., Android 4.0 Ice Cream Sandwich or Android 6.0 Marshmallow) are you running?  Is it
 the stock
version from the manufacturer or a custom ROM?

**Screenshots:**

Screenshot 2023-03-16 at 23 03 54

### PR DESCRIPTION
**Pull request by gururani-abhishek**
Fixes #2000 

Fixed the logic of comparator function that used to sort nofications(desc order) on the basis of their timestamps.

The comparator function that is called in DatabaseHelper.kt to sort the notifications in Descending order of their timestamp is incorrect and doesn't provide the right comparator function logic to sort objects in descending order. According to online java/kotlin documentation a comparator function should provide return values for all three cases.

1. updated the comparator function to provide return values for all three conditions(a > b ,a < b and a == b), where a and b are timestamps of any two notifications that are being compared.

Please Add Screenshots If there are any UI changes.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by gururani-abhishek** [comment]
Hey @jawidMuhammadi, please have a look :)
Further attaching an [online guide](https://clojure.org/guides/comparators) on Comparator Functions that more or less summaries my research on "Comparator Functions" that I did to solve this issue with our codebase.

File: app/src/main/java/org/mifos/mobile/utils/NotificationComparator.kt [hunk 1]
```diff
@@ -9,9 +9,10 @@ import java.util.*
 class NotificationComparator : Comparator<MifosNotification> {
     override fun compare(mifosNotification1: MifosNotification, mifosNotification2: MifosNotification): Int {
         return when {
+            // comparator function logic to sort notifications in the descending order of their timeStamp :
             mifosNotification2.timeStamp < mifosNotification1.timeStamp -> -1
-            mifosNotification1.timeStamp > mifosNotification2.timeStamp -> 1
+            mifosNotification1.timeStamp < mifosNotification2.timeStamp -> 1
```
Comment (jawidMuhammadi) [inline app/src/main/java/org/mifos/mobile/utils/NotificationComparator.kt]: Great catch! However, both comparators are the same in line number 13 and 14, it is difficult to understand it for developers (although it's technically correct). Let's rename `mifosNotification1` variable to something like `firstNotification` and the other one to `secondNotificaiton`
then do the comparison like:
 `firstNotification.timpeStamp > secondNotificaiton.timeStamp` and 
`firstNotification.timpeStamp < secondNotificaiton.timeStamp `

**Review by jawidMuhammadi — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobile/utils/NotificationComparator.kt (hunk 1 above)
Comment (gururani-abhishek) [reply app/src/main/java/org/mifos/mobile/utils/NotificationComparator.kt]: Thank you @jawidMuhammadi, I made the required changes : )

**Review by jawidMuhammadi — APPROVED** [review]
Looks Good To Me! :)
