### PR TITLE
Fix #898: Submission/Disbursement date pickers

### LINKED ISSUE #898: Working of DatePicker on creating Loans are causing Inconsistency
**Summary:**

Working of Calender on creating Loans are causing Inconsistency

**Steps to reproduce:**

Create a new loan

**Expected behaviour:**

Submission date should show the "Present Date" and ImageView should be removed
Whereas for Expected Disbursement should show the dates after "Present Date" as selectable, and previos dates as non-selectable.

**Observed behaviour:**

Both Datepickers are selectable to previous dates of "Present Date"

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

### PR DESCRIPTION
**Pull request by migueldinisdev**
Fixes #898 

image
_Updated (pencil was removed) - the rest is the same, look at the above gif_

- Submission Date is now not using a DatePicker because it should not be selectable
- Expected Disbursement Date is using a DatePicker where we can only choose the future and the current day
- Some grammar errors fixed in variables' names
- Created constants in **MFDatePicker** so that it supports the choice of what **type** of calendar we want to instantiate:
- - `ALL_DAYS` -> Any day can be selected
- - `STARTS_CURRENT_DAY` -> Days starting the current day can be selected
- - `ENDS_CURRENT_DAY` -> Days until current day can be selected
- - `ONLY_CURRENT_DAY` -> Only the current day can be selected
- Fixed all `newInstance(this)` cases where a new argument was needed - in this case, the constant.

Example of use:

`mfDatePicker = MFDatePicker.newInstance(this, MFDatePicker.ALL_DAYS);`

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@MigDinny Add a GIF.

**Comment by migueldinisdev** [comment]
@miPlodder I thought of that too but I didn’t for a few reasons:

- I’m using an emulator, it is slow, I’m not sure if I record the screen it will get slower
- there were no changes to the UI
- we do not notice anything after opening add loans fragment, because when we click on submission date nothing happens, so, the gif would be more of a screenshot

I don’t think it’s necessary to post a gif in this particular situation. What do you think?

**Comment by migueldinisdev** [comment]
But anyway, I’ll see if I can record my screen. It’s an emulator and my pc would almost crash if I record it but I can try. I’m using an iPhone, that’s why I don’t do it on my phone.

What tools do you use for recording and conversion to GIF?

**Comment by miPlodder** [comment]
@MigDinny UI changes like no Datepicker is shown for picking Today's date and Disbursement Date selectable dates. Add a GIF. Use an Android device for debugging. It's faster. And use any screen recorder app from play store.

**Comment by migueldinisdev** [comment]
@miPlodder Done!

File: app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java [hunk 1]
```diff
@@ -28,7 +28,14 @@
     static Calendar calendar;
     private String startDateString;
     private long startDate;
-    private boolean isStartOrEnd;
+    //private boolean isStartOrEnd;
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java]: Please remove this comment

File: app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java [hunk 2]
```diff
@@ -74,12 +87,28 @@ public Dialog onCreateDialog(Bundle savedInstanceState) {
...
+
+            case ENDS_CURRENT_DAY:
+                dialog.getDatePicker().setMaxDate(new Date().getTime());
+                break;
+
+            case ALL_DAYS:
+                // nothing is set. datePicker by default allows the selection of any day
+                break;
         }
+
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java]: Remove this line

**Comment by migueldinisdev** [comment]
@luckyman20 Removed the lines you asked. I'm just waiting for Travis.

File: app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java [hunk 3]
```diff
@@ -74,11 +86,26 @@ public Dialog onCreateDialog(Bundle savedInstanceState) {
...
+            case STARTS_CURRENT_DAY:
+                dialog.getDatePicker().setMinDate(new Date().getTime());
+                break;
+
+            case ENDS_CURRENT_DAY:
+                dialog.getDatePicker().setMaxDate(new Date().getTime());
+                break;
+
+            case ALL_DAYS:
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java]: We don't want this last case, as we are doing nothing here.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java [hunk 4]
```diff
@@ -154,7 +156,7 @@ public void onCreate(Bundle savedInstanceState) {
 
     @Override
     public View onCreateView(LayoutInflater inflater, ViewGroup container,
-            Bundle savedInstanceState) {
+                             Bundle savedInstanceState) {
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java]: Remove these kind of changes in the PR.

Comment (migueldinisdev) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java]: Don't know what happened there... probably IDE stuff.

File: app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java (hunk 3 above)
Comment (migueldinisdev) [reply app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java]: I created that case in order to prevent bugs... but I'll remove it and will see if there is no problem.

**Comment by migueldinisdev** [comment]
@luckyman20 I removed the ALL_DAYS case. Although, I cannot remove the constant. It is needed for compatibility. Whenever "ALL_DAYS" is selected, nothing happens anyway, just like the old behavior. Removing the constant would cause some bugs I've detected to happen and this is the best way to handle this situation. Anyways, `case ALL_DAYS` was removed.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java [hunk 5]
```diff
@@ -95,15 +95,17 @@
     private ArrayAdapter<String> loanPurposeAdapter;
 
     private LoanTemplate loanTemplate;
-    private DialogFragment mfDatePicker;
+    private DialogFragment mfDatePickerDisbursement = MFDatePicker.newInstance(
+            this, MFDatePicker.STARTS_CURRENT_DAY);
+    private DialogFragment mfDatePickerSubmission = MFDatePicker.newInstance(
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java]: If you are initialising these in the methods then why are you initialising them here. Also, we would need any one `DialogFragment` as they are then initialised in their respective methods.

**Comment by migueldinisdev** [comment]
@luckyman20 done

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java [hunk 6]
```diff
@@ -338,7 +337,7 @@ private void filter(long startDate , long endDate) {
 
         dummyTransactionList = new ArrayList<>(transactionsList);
         savingAccountsTransactionPresenter.filterTransactionList(dummyTransactionList ,
-                                                                    startDate , endDate);
+                startDate , endDate);
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java]: Undo this change

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java [hunk 7]
```diff
@@ -155,7 +155,7 @@ public void showUserInterface() {
      */
     @Override
     public void showSavingAccountsDetail(SavingsWithAssociations
-                                                     savingsWithAssociations) {
+                                                 savingsWithAssociations) {
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java]: Undo this too

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java (hunk 6 above)
Comment (migueldinisdev) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java]: Android Studio is doing that, not me. I will fix that but I suggest to let the next things like those ones be merged. If Android Studio is doing that, it's because of some reason...

**Comment by migueldinisdev** [comment]
@luckyman20 done

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java [hunk 8]
```diff
@@ -295,15 +294,14 @@ void onRetry() {
      * Initializes {@code tvSubmissionDate} with current Date
      */
     public void inflateSubmissionDate() {
-        mfDatePicker = MFDatePicker.newInsance(this);
```
Comment (luckyman20) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java:298]: You haven't initialised the date picker here, so how will it work. Please do.

**Comment by migueldinisdev** [comment]
@luckyman20 done

**Comment by miPlodder** [comment]
@MigDinny Instead of disabling Present DatePicker, replace the DatePicker with a TextView that is showing the present date.

**Comment by migueldinisdev** [comment]
@miPlodder ?

What do you mean?

**Comment by miPlodder** [comment]
@MigDinny I meant that remove the ImageView next to the Current Date TextView.

File: app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java [hunk 9]
```diff
@@ -28,7 +28,13 @@
     static Calendar calendar;
     private String startDateString;
     private long startDate;
-    private boolean isStartOrEnd;
+    private int datePickerType = ALL_DAYS;
+
+    /* Constants used to select which type of date picker is being called */
+    public static final int ONLY_CURRENT_DAY = 0; // only current day can be picked
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java]: This is not needed, as if no date is to be selected then why to show date picker.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java [hunk 10]
```diff
@@ -95,15 +95,15 @@
     private ArrayAdapter<String> loanPurposeAdapter;
 
     private LoanTemplate loanTemplate;
-    private DialogFragment mfDatePicker;
+    private DialogFragment mfDatePickerDisbursement;
+    private DialogFragment mfDatePickerSubmission;
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java]: Remove this

**Comment by migueldinisdev** [comment]
> @MigDinny I meant that remove the ImageView next to the Current Date TextView.

I tried to do it but I couldn't. Can't find its declaration in the code to remove it. Could you give me a hint?

(you mean the pencil right?)

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java (hunk 10 above)
Comment (migueldinisdev) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java]: And what should I use to replace them? They are being used... Should I use a `mfDatePicker` for both cases?

**Comment by miPlodder** [comment]
> > @MigDinny I meant that remove the ImageView next to the Current Date TextView.
> 
> I tried to do it but I couldn't. Could you give me a hint?

Do some research and give it a try. If I will give you hint you wouldn't learn. It takes time to find optimal solutions, so don't give up that easily.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java (hunk 10 above)
Comment (MigDinny) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java]: > And what should I use to replace them? They are being used... Should I use a `mfDatePicker` for both cases?

^^^^

@miPlodder

**Comment by migueldinisdev** [comment]
@miPlodder 

> And what should I use to replace them? They are being used... Should I use a mfDatePicker for both cases?

?

**Comment by migueldinisdev** [comment]
@miPlodder done

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java [hunk 11]
```diff
@@ -145,7 +145,7 @@ public void showUserInterface() {
         rvSavingAccountsTransaction.setAdapter(transactionListAdapter);
 
         radioGroup.setOnCheckedChangeListener(this);
-        mfDatePicker = MFDatePicker.newInsance(this);
+        mfDatePicker = MFDatePicker.newInstance(this, MFDatePicker.ALL_DAYS);
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java:148]: Set it to the present and future.

File: app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java [hunk 12]
```diff
@@ -51,11 +56,17 @@
...
-        isStartOrEnd = true;
+
     }
 
-    public static MFDatePicker newInsance(Fragment fragment) {
+    public static MFDatePicker newInstance(Fragment fragment, int datePickerType) {
         MFDatePicker mfDatePicker = new MFDatePicker();
+
+        Bundle args = new Bundle();
+        args.putInt("datePickerType", datePickerType);
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java]: Add this string to Constants.java file and use it here.

**Review by miPlodder — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java [hunk 13]
```diff
@@ -295,15 +295,13 @@ void onRetry() {
...
-        mfDatePicker = MFDatePicker.newInsance(this);
         tvSubmissionDate.setText(MFDatePicker.getDatePickedAsString());
     }
 
     /**
      * Initializes {@code tvExpectedDisbursementDate} with current Date
      */
     public void inflateDisbursementDate() {
-        mfDatePicker = MFDatePicker.newInsance(this);
         tvExpectedDisbursementDate.setText(MFDatePicker.getDatePickedAsString());
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/LoanApplicationFragment.java:305]: Initialization works needs to done here, not above for `mfDatePicker`

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java [hunk 14]
```diff
@@ -145,7 +145,7 @@ public void showUserInterface() {
         rvSavingAccountsTransaction.setAdapter(transactionListAdapter);
 
         radioGroup.setOnCheckedChangeListener(this);
-        mfDatePicker = MFDatePicker.newInsance(this);
+        mfDatePicker = MFDatePicker.newInstance(this, MFDatePicker.STARTS_CURRENT_DAY);
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsTransactionFragment.java]: Change here, a user should be able to select past and present dates.

File: app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java [hunk 15]
```diff
@@ -28,7 +28,12 @@
     static Calendar calendar;
     private String startDateString;
     private long startDate;
-    private boolean isStartOrEnd;
+    private int datePickerType = ALL_DAYS;
+
+    /* Constants used to select which type of date picker is being called */
+    public static final int ENDS_CURRENT_DAY = 1; // only current day and future can be picked
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/utils/MFDatePicker.java]: Rename these static fields, so that they are automatically understandable. (PREVIOUS_DAYS, FUTURE_DAYS)

File: app/src/main/res/layout/fragment_add_loan_application.xml [hunk 16]
```diff
@@ -156,10 +156,6 @@
                         android:layout_width="wrap_content"
                         android:layout_height="wrap_content"
                         android:textAppearance="@style/Base.TextAppearance.AppCompat.Medium"/>
```
Comment (miPlodder) [inline app/src/main/res/layout/fragment_add_loan_application.xml:159]: Align the Submission TextView, with Disbursement fields.

**Review by miPlodder — CHANGES_REQUESTED** [review]

File: app/src/main/res/layout/fragment_add_loan_application.xml (hunk 16 above)
Comment (migueldinisdev) [reply app/src/main/res/layout/fragment_add_loan_application.xml:159]: That's the problem I faced. I can remove the ImageView but I cannot align them.

**Comment by luckyman20** [comment]
@MigDinny Squash the commits.

**Comment by migueldinisdev** [comment]
@luckyman20 done. i forgot to do it

**Review by miPlodder — APPROVED** [review]
