### PR TITLE
Fix: #894: Progress Bar shown on top of Input Fields

### LINKED ISSUE #894: Progress Bar shown on top of Input Fields
**Summary:**

Progress Bar shown on top of Input Fields

**Steps to reproduce:**

Go to Beneficiary. Click any Beneficiary from the list.

**Expected behaviour:**

Input fields should be absent and when fetching (progress bar) is done, then it should be made visible.

**Observed behaviour:**

Instead, Progress Bar is shown on top of Input Fields which is a bad UI design.

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

### PR DESCRIPTION
**Pull request by etlhsu**
Fixes #894

My solution makes sure that the progress bar is never laid on top of the UI. I achieved this functionality by hiding the UI, whenever the loading spinner is been called to show its progress, and then redisplaying the UI after the UI has loaded up.

image

### CODE REVIEW

**Comment by etlhsu** [comment]
@miPlodder, can you provide further feedback on my solution (ex. the location of the solution). I would like to be able to improve the quality and clarity of my solution as much as possible!

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java [hunk 1]
```diff
@@ -320,6 +321,8 @@ public void showError(String msg ) {
     @Override
     public void showProgress() {
         showProgressBar();
+        llApplicationBeneficiary.setVisibility(View.GONE);
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java]: This is not a good place to add this line. This method should only do what it is named.

**Review by miPlodder — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java (hunk 1 above)
Comment (etlhsu) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java]: @miPlodder I see what you are recommending, I should do the manipulation within the presenter, not the fragment.

File: app/src/main/java/org/mifos/mobilebanking/presenters/BeneficiaryApplicationPresenter.java [hunk 2]
```diff
@@ -78,6 +80,7 @@ public void onError(Throwable e) {
                     public void onNext(BeneficiaryTemplate beneficiaryTemplate) {
                         getMvpView().hideProgress();
                         getMvpView().showBeneficiaryTemplate(beneficiaryTemplate);
+                        getMvpView().setVisibility(View.VISIBLE);
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/presenters/BeneficiaryApplicationPresenter.java]: Add this inside `onComplete()`

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java [hunk 3]
```diff
@@ -317,9 +317,15 @@ public void showError(String msg ) {
...
 
+    @Override
+    public void setVisibility(int state) {
+        llApplicationBeneficiary.setVisibility(state);
+    }
+
     @Override
     public void showProgress() {
         showProgressBar();
+
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java]: Remove this new line.

File: app/src/main/java/org/mifos/mobilebanking/presenters/BeneficiaryApplicationPresenter.java (hunk 2 above)
Comment (etlhsu) [reply app/src/main/java/org/mifos/mobilebanking/presenters/BeneficiaryApplicationPresenter.java]: @miPlodder I addressed your change 😄

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java (hunk 3 above)
Comment (etlhsu) [reply app/src/main/java/org/mifos/mobilebanking/ui/fragments/BeneficiaryApplicationFragment.java]: @miPlodder I addressed your change 😄

File: app/src/main/java/org/mifos/mobilebanking/presenters/BeneficiaryApplicationPresenter.java (hunk 2 above)
Comment (miPlodder) [reply app/src/main/java/org/mifos/mobilebanking/presenters/BeneficiaryApplicationPresenter.java]: Remove this from `onNext()`

Comment (etlhsu) [reply app/src/main/java/org/mifos/mobilebanking/presenters/BeneficiaryApplicationPresenter.java]: @miPlodder I now see what you mean, I am using the methods innocrectly, onNext() does work to prepare the UI, and onComplete() finishes the process

**Comment by etlhsu** [comment]
@miPlodder I added the last bit of your edits, can you resolve the issue and make sure my request is ready for merging?

**Review by miPlodder — APPROVED** [review]
