### PR TITLE
Fix #897: Username is shown as null on login

### LINKED ISSUE #897: Username is shown as "null" on login
**Summary:**

Username is shown as "null" on login

**Steps to reproduce:**

Login to app

**Expected behaviour:**

Username should be shown

**Observed behaviour:**

Username is shown as null

**Device and Android version:**

Xiaomi, Marshmallow

**Screenshots:**

### PR DESCRIPTION
**Pull request by etlhsu**
Fixes #897

The welcome toast shows the "Welcome" with the username, instead of "Welcome null". I solved the issue by addressing an error in the Retrofit implementation. The change helps Retrofit recognize the field properly.
screenshot_20181023-215845

### CODE REVIEW

**Comment by etlhsu** [comment]
@miPlodder, I believe my pull request is ready to merge. Can you help merge it or give me any improvements needed?

File: app/src/main/java/org/mifos/mobilebanking/models/User.kt [hunk 1]
```diff
@@ -11,6 +12,7 @@ data class User (
 
     var userId: Long = 0,
     var isAuthenticated: Boolean = false,
+    @SerializedName(value = "username")
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobilebanking/models/User.kt]: @ethan627hsu It's also a correct solution. But Instead, rename `userName` to `username`.

Comment (etlhsu) [reply app/src/main/java/org/mifos/mobilebanking/models/User.kt]: My solution has an advantage over the brute force, I don't have to refactor getters and setters across different files. My solution causes the least amount of overlap with different files.

Comment (miPlodder) [reply app/src/main/java/org/mifos/mobilebanking/models/User.kt]: I know that, but it's just a typing mistake.

Comment (etlhsu) [reply app/src/main/java/org/mifos/mobilebanking/models/User.kt]: So your suggesting that I rename the field and refactor it across all of its references?

Comment (miPlodder) [reply app/src/main/java/org/mifos/mobilebanking/models/User.kt]: Yes, moreover it not used much.

**Comment by etlhsu** [comment]
@miPlodder, I successfully implemented your strategy. Can you review my pull request for any other need modifications before merging?

**Comment by miPlodder** [comment]
@ethan627hsu Good job. Submit your task, I will approve it.
