### PR TITLE
fix: Consistent UI for Apply for Loan with no internet. 

### LINKED ISSUE #1075: Consistent UI for Apply for Loan with no internet.
**Summary:**

With no internet, all the other screens show the same screen as the first screenshot, while the Apply for Loan shows a different screen.

**Steps to reproduce:**

Turn off data/wifi -> Apply for Loan

**Expected behaviour:**

The design should be consistent.

**Observed behaviour:**

Inconsistent design.

**Device and Android version:**

Redmi Note 3

**Screenshots:**
screenshot_2019-02-27-17-13-45-118_org mifos mobilebanking

screenshot_2019-02-27-17-13-40-713_org mifos mobilebanking

### PR DESCRIPTION
**Pull request by kmanikanta335**
Fixes #1075  

 Screenshots of UI changes.

https://github.com/openMF/mifos-mobile/assets/118070186/8b6dabbb-b731-4a3c-8ea4-bc8e280bdbc5

Please make sure these boxes are checked before submitting your pull request - thanks!

- ✅  Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- ✅  Run the unit tests with `./gradlew check` to make sure you didn't break anything

- ✅  If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

File: app/src/main/java/org/mifos/mobile/ui/fragments/LoanApplicationFragment.kt [hunk 1]
```diff
@@ -322,11 +324,20 @@ class LoanApplicationFragment : BaseFragment() {
...
+                binding.viewFlipper,
+                binding.layoutError.root,
+            )
+            loadLoanTemplate()
+        } else {
+            Toast.makeText(
+                context,
+                getString(R.string.internet_not_connected),
+                Toast.LENGTH_SHORT,
+            ).show()
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/fragments/LoanApplicationFragment.kt]: can we show toaster here instead of a toast ?

File: app/src/main/java/org/mifos/mobile/ui/fragments/LoanApplicationFragment.kt [hunk 2]
```diff
@@ -546,16 +557,17 @@ class LoanApplicationFragment : BaseFragment() {
...
-            }
+        if (!Network.isConnected(context)) {
+            sweetUIErrorHandler?.showSweetNoInternetUI(binding.viewFlipper, binding.layoutError.root)
+        } else {
+            sweetUIErrorHandler?.showSweetErrorUI(
+                message,
+                binding.viewFlipper,
+                binding.layoutError.root,
+            )
+            Toast.makeText(context, message, Toast.LENGTH_SHORT).show()
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/ui/fragments/LoanApplicationFragment.kt]: same here

**Comment by PratyushSingh07** [comment]
Also make sure that you follow the PR & commit guidelines.  The commit message should have been `fix #1075: ui layout for loan application fragment` instead of `fix:error layout`.
To change your commit message you can use git amend

**Comment by kmanikanta335** [comment]
@PratyushSingh07 pls review it

**Comment by PratyushSingh07** [comment]
LGTM!! We can merge this @therajanmaurya

**Comment by kmanikanta335** [comment]
@therajanmaurya pls review and merge it .

Will mifos-mobile take part in gsoc 2024 ?

**Comment by therajanmaurya** [comment]
> Also make sure that you follow the PR & commit guidelines. The commit message should have been `fix #1075: ui layout for loan application fragment` instead of `fix:error layout`.
> To change your commit message you can use git amend

Yes
