### PR TITLE
fixIssue#629:Null is not shown as currency type in Recent transactions

### LINKED ISSUE #629: In recent transactions null is shown in Currency type.
**Summary:**

In recent transactions null is shown in Currency type.

**Steps to reproduce:**

Go to recent transactions.

**Expected behaviour:**

At place of null currency value should be there.

**Observed behaviour:**

Null was shown instead of currency type.

**Device and Android version:**
Moto g-3 (6.0.1)

**Screenshots:**
screenshot_20180215-042322

### PR DESCRIPTION
**Pull request by ivary43**
Fixes #629 

Please Add Screenshots If any UI changes.
screenshot_20180217-014430

Please make sure these boxes are checked before submitting your pull request - thanks!

- \[x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- \[x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- \[x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ivary43** [comment]
@dilpreet96 , @therajanmaurya , @droidchef please review.

File: app/src/main/java/org/mifos/mobilebanking/models/client/Currency.java [hunk 1]
```diff
@@ -58,6 +58,9 @@ public void setDecimalPlaces(Integer decimalPlaces) {
     }
 
     public String getDisplaySymbol() {
+        if (displaySymbol == null) {
+            return code;
```
Comment (therajanmaurya) [inline app/src/main/java/org/mifos/mobilebanking/models/client/Currency.java:62]: Good 👍

**Review by therajanmaurya — APPROVED** [review]
