### PR TITLE
Fix 461: Enhancement in Accounts Section

### LINKED ISSUE #461: In Saving Account Details, when offline, error message is not aligned properly
**Summary:**

If a User is offline, and user goes to Saving Account Details, the error is not aligned well

**Steps to reproduce:**

Home --> Accounts --> Any Saving Accounts

**Expected behavior:**

Error message should be aligned properly.

**Observed behavior:**

Error message is showing at top center position, icon and text are colliding. 

**Device and Android version:**

Coolpad Cool 1 (Android 6.0.1 Marshmallow)

**Screenshots:**

screenshot_20171015-220345

@naman14 @therajanmaurya @dilpreet96 Can I work on this issue ?

### PR DESCRIPTION
**Pull request by miPlodder**
Fixes #461 #550 #549 #461 

pr_account1
pr_account2
pr_account3
pr_account4

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by miPlodder** [comment]
@therajanmaurya I have extended the issue and worked on Account Section Enhancement. Please review this PR.

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/AccountsFragment.java [hunk 1]
```diff
@@ -367,11 +372,14 @@ public void filterShareAccount(List<CheckboxStatus> statusModelList) {
      */
     @Override
     public void showError(String errorMessage) {
-        ll_error.setVisibility(View.VISIBLE);
-        rvAccounts.setVisibility(View.GONE);
-        noAccountText.setText(errorMessage);
-        noAccountIcon.setImageResource(R.drawable.ic_error_black_24dp);
-        Toast.makeText(getActivity(), errorMessage, Toast.LENGTH_SHORT).show();
+        if (!Network.isConnected(getContext())) {
+            rvAccounts.setVisibility(View.GONE);
```
Comment (therajanmaurya) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/AccountsFragment.java]: @miPlodder I don't think this line make any sense.
`
 rvAccounts.setVisibility(View.GONE);
` 
because we are passing `rvAccount` in showSweetNoInternetUI().. method to visibility GONE.

**Review by therajanmaurya — CHANGES_REQUESTED** [review]

**Comment by therajanmaurya** [comment]
@miPlodder Rest of thing looks good, please make above changes.

**Comment by miPlodder** [comment]
@therajanmaurya I have made the changes. Please review again.

**Review by therajanmaurya — APPROVED** [review]

**Comment by miPlodder** [comment]
@therajanmaurya #550 #549 #461 These are the issues.
