### PR TITLE
fix #2448 Handle network error in HomeViewModel to emit error event

### LINKED ISSUE #2448: Issue : the Failed to fetch details  dialogue appears constantly multiple times
**Summary:**

 the Failed to fetch details  dialogue appears constantly multiple times  when the internet is not connected

turn of the internet and try to refresh the home page

**Expected behaviour:**
it should disappear when it was clicked ok!

**Device and Android version:**
Pixel 5a

**Screenshots:**

https://github.com/openMF/mifos-mobile/assets/136256522/7f48c800-9f36-4a43-91fa-9d2b5ce75413

### PR DESCRIPTION
**Pull request by ghost**
Fixes #2448 

https://github.com/openMF/mifos-mobile/assets/136256522/449e8790-333f-4580-8249-9d0965e39c24

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by ghost** [comment]
@PratyushSingh07 Can you review this...

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt [hunk 1]
```diff
@@ -30,17 +30,25 @@ class HomeViewModel @Inject constructor(private val homeRepositoryImp: HomeRepos
     fun loadClientAccountDetails() {
         viewModelScope.launch {
             _homeUiState.value = HomeUiState.Loading
-            homeRepositoryImp.clientAccounts().catch {
-                _homeUiState.value = HomeUiState.Error(R.string.error_fetching_accounts)
+            var errorHandled = false // Variable to track whether the error has been handled
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: Remove the comment from here. Use lateinit to define this variable and then initialise it later

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt [hunk 2]
```diff
@@ -30,17 +30,25 @@ class HomeViewModel @Inject constructor(private val homeRepositoryImp: HomeRepos
...
+
+            homeRepositoryImp.clientAccounts().catch { e ->
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: Are we using `e` ? If not then we can get rid of it

**Comment by PratyushSingh07** [comment]
In the video that you have attached I see that the snackbar still appears twice before it eventually stops. Is this the supposed behaviour? I mean it should have just appeared once , isn't?

**Review by PratyushSingh07 — CHANGES_REQUESTED** [review]

**Comment by ghost** [comment]
@PratyushSingh07 Two Snack bars were one for the failed to fetch client another for Accounts if you want me to remove of them i can...

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt (hunk 2 above)
Comment (ghost) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: Okay! removing it

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt (hunk 1 above)
Comment (ghost) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: `fun loadClientAccountDetails() {
        viewModelScope.launch {
            _homeUiState.value = HomeUiState.Loading

            var errorHandled by Delegates.notNull<Boolean>() 

            homeRepositoryImp.clientAccounts().catch {
                errorHandled = true 
                _homeUiState.value = HomeUiState.Error(R.string.error_fetching_accounts)
            }.collect { clientAccounts ->
                if (!errorHandled) {
                    _homeUiState.value = HomeUiState.ClientAccountDetails(
                        getLoanAccountDetails(clientAccounts.loanAccounts),
                        getSavingAccountDetails(clientAccounts.savingsAccounts)
                    )
                }
            }
        }
    }
`
Like this..?

if i declare it Normally lateint its giving me error or  we can use nullable variable

Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: on 2nd thought lets just continue with what you have done . You wont be able to use lateinit with primitive types. Just make your variable global and we will be good to go !!

**Comment by PratyushSingh07** [comment]
> @PratyushSingh07 Two Snack bars were one for the failed to fetch client another for Accounts if you want me to remove of them i can...

Hmm, Well ideally we should also show "No internet connection" in our snackbar.  So i think we can show 2 snackbars. The first one that says no internet connection(We may have a string already defined for this.) & the other say that says failed to fetch accounts

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt (hunk 1 above)
Comment (ghost) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: @PratyushSingh07 Its giving me error even When I make it Global variable....I Guess the Above method would be Good!

**Comment by ghost** [comment]
@PratyushSingh07 Made the requested changes..!

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt [hunk 3]
```diff
@@ -26,21 +26,29 @@ class HomeViewModel @Inject constructor(private val homeRepositoryImp: HomeRepos
...
     val homeUiState: StateFlow<HomeUiState> = _homeUiState
-
+    var errorHandled = false
     fun loadClientAccountDetails() {
         viewModelScope.launch {
             _homeUiState.value = HomeUiState.Loading
-            homeRepositoryImp.clientAccounts().catch {
-                _homeUiState.value = HomeUiState.Error(R.string.error_fetching_accounts)
+
+
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: remove this extra space

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt [hunk 4]
```diff
@@ -26,21 +26,29 @@ class HomeViewModel @Inject constructor(private val homeRepositoryImp: HomeRepos
...
+            homeRepositoryImp.clientAccounts().catch { 
+                if (!errorHandled) {
```
Comment (PratyushSingh07) [inline app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: do we need this condition ? I mean the purpose of catch api itself is to catch any exception that has occurred in flows execution

**Review by PratyushSingh07 — CHANGES_REQUESTED** [review]
Also make sure to format your code with `ctrl+shift+L` if you haven't already @Thanush66

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt (hunk 4 above)
Comment (ghost) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: The condition if (!errorHandled) is there to ensure that the error-handling block inside the catch block is executed only if errorHandled is false. This is likely done to prevent redundant error handling and ensure that the error state is set only once.

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt (hunk 3 above)
Comment (ghost) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: done

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt (hunk 4 above)
Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: sorry but I didn't understand this explanation. If I am inside the catch block then how is it making error handling redundant ?

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt (hunk 3 above)
Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: please dont resolve the conversation on your own @Thanush66 .

File: app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt (hunk 4 above)
Comment (Thanush66) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt:36]: The condition if (!errorHandled) checks whether the error handling logic inside the catch block should be executed. If errorHandled is true, it means that the error has already been handled, and there is no need to handle it again.
the issue is (the Failed to fetch details dialogue appears constantly multiple times) right....it ensures the snack bar appears  pnly once..

Comment (ghost) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: @PratyushSingh07 Yeah its working fine even though the if statements are removed....ig there is no issue it was my problem

Comment (PratyushSingh07) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: Then add another commit that fixes these changes

Comment (ghost) [reply app/src/main/java/org/mifos/mobile/viewModels/HomeViewModel.kt]: Done!

**Review by PratyushSingh07 — APPROVED** [review]
LGTM
