### PR TITLE
fix : Minimum required balance label hidden on null data

### LINKED ISSUE #465: In Saving Account Details, Min. Required Bal. field shouldn't be empty
**Summary:**

When a user is checking a saving account Min Required Balance is empty because it was not specified when creating the account.

**Steps to reproduce:**

Home --> Accounts --> Any Savings Account

**Expected behavior:**

If there was no Min. Required Balance specified at the time of creating the savings account. Then Min. Required Balance should show `Not Applicable`

**Observed behavior:**

The Min. Required Balance is empty in many savings account as it was not specified at time of creating the savings account

**Device and Android version:**

Coolpad Cool 1 (Android 6.0.1 Marshmallow)

**Screenshots:**

screenshot_20171016-112636 1

@therajanmaurya @dilpreet96 Can I work on this issue ?

### PR DESCRIPTION
**Pull request by geekanamika**
Fixes #465
screenshot_2018-01-28-23-37-39-567_org mifos mobilebanking
screenshot_2018-01-28-23-37-51-107_org mifos mobilebanking

### CODE REVIEW

File: app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsDetailFragment.java [hunk 1]
```diff
@@ -84,6 +84,9 @@
     @BindView(R.id.tv_status)
     TextView tvStatus;
 
+    @BindView(R.id.tv_minRequiredBalance)
+    TextView minRequiredBalanceLabel;
```
Comment (dilpreet2028) [inline app/src/main/java/org/mifos/mobilebanking/ui/fragments/SavingAccountsDetailFragment.java]: @geekanamika , can you rename it as `tvMinRequiredBalanceLabel`

**Review by dilpreet2028 — CHANGES_REQUESTED** [review]

**Comment by geekanamika** [comment]
@dilpreet96 I have updated it, Can you please review now ? Thank you

**Review by dilpreet2028 — APPROVED** [review]
