### PR TITLE
Fixes #1073: Toast message in Recent Transactions fixed

### LINKED ISSUE #1073: Wrong Toast message in Recent Transactions
**Summary:**

Opening Recent Transactions shows "No more transactions available" on opening. It should only be prompted when a list is scrolled down.

**Steps to reproduce:**

Navigation Drawer->Recent Transactions

**Expected behaviour:**

The toast message should be shown only when a list is scrolled down.

**Observed behaviour:**

The toast message is shown.

**Device and Android version:**

Redmi Note 3

**Screenshots:**
screenshot_2019-02-27-00-06-40-873_org mifos mobilebanking

### PR DESCRIPTION
**Pull request by PatelVatsalB21**
Fixes #1073 
Now message is shown only when user scrolls for more items.

GIF-201217_111940 1

- [x] Apply the `AndroidStyle.xml` style template to your code in Android Studio.

- [x] Run the unit tests with `./gradlew check` to make sure you didn't break anything

- [x] If you have multiple commits please combine them into one commit by squashing them.

### CODE REVIEW

**Comment by PatelVatsalB21** [comment]
@miPlodder plz review this pr.

File: app/src/main/java/org/mifos/mobile/ui/fragments/RecentTransactionsFragment.kt [hunk 1]
```diff
@@ -112,6 +113,14 @@ class RecentTransactionsFragment : BaseFragment(), RecentTransactionsView, OnRef
                     override fun onLoadMore(page: Int, totalItemsCount: Int, view: RecyclerView?) {
                         recentTransactionsPresenter?.loadRecentTransactions(true, totalItemsCount)
                     }
+
+                    override fun onScrollStateChanged(recyclerView: RecyclerView, newState: Int) {
+                        super.onScrollStateChanged(recyclerView, newState)
+                        if (!recyclerView.canScrollVertically(1) &&
+                                newState==RecyclerView.SCROLL_STATE_IDLE) {
```
Comment (miPlodder) [inline app/src/main/java/org/mifos/mobile/ui/fragments/RecentTransactionsFragment.kt]: format the code before pushing in IDE
Rest looks good

**Review by miPlodder — CHANGES_REQUESTED** [review]

**Comment by PatelVatsalB21** [comment]
@miPlodder please review changes

**Review by miPlodder — APPROVED** [review]
